# Generated by Django 5.0.6 on 2024-06-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorphoto', models.ImageField(upload_to='')),
                ('doctorname', models.CharField(max_length=200)),
                ('doctoremail', models.CharField(max_length=200)),
                ('doctorphone', models.CharField(max_length=200)),
                ('doctorqualification', models.CharField(max_length=200)),
                ('doctor_dutystart', models.CharField(max_length=200)),
                ('doctor_dutyend', models.CharField(max_length=200)),
                ('doctor_suggestion', models.CharField(max_length=200)),
                ('doctor_fees', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
