# Generated by Django 5.0.6 on 2024-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0002_doctor_details_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(max_length=100)),
                ('patient_doctor', models.CharField(max_length=100)),
                ('patient_date', models.CharField(max_length=100)),
                ('patient_problem', models.CharField(max_length=200)),
            ],
        ),
    ]
