# Generated by Django 5.0.6 on 2024-07-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0003_appoinment'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoinment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(max_length=100)),
                ('patient_doctor', models.CharField(max_length=100)),
                ('patient_date', models.CharField(max_length=100)),
                ('patient_problem', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='appoinment',
        ),
    ]
