# Generated by Django 5.0.6 on 2024-07-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0004_appoinment_details_delete_appoinment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appoinment_details',
        ),
    ]
